### ISSUE TITLE
Fix margin and padding and improve colour scheme

### ISSUE THREAD

**Issue by pulkit-30** [pulkit-30/Frontend-Animations#44]
<img width="1680" alt="Screenshot 2021-10-06 at 1 03 12 AM" src="https://user-images.githubusercontent.com/76155456/136090635-960edc00-23fd-4d5f-bf59-5b989b357671.png">

**Comment by Sarthaknegigit** [comment]
assign me this issue

**Comment by shingtesuyash** [comment]
I would like to contribute on this project ? Kindly assign me this project.

**Comment by pulkit-30** [comment]
@Sarthaknegigit I am assigning you this issue.
